### ISSUE TITLE
Nummern unsynchron

### ISSUE THREAD

**Issue by klaussoft** [Gravitar64/A-beautiful-code-in-Python#10]
Die Videonummern 45-48 sind zwischen Github und Youtube nicht synchron.
Desweiteren fehlt das angekündigte Video zum Knacken der Enigma. Die Scriptdatei dazu ist allerdings da. Ist das eventuell ein Fehler? Da das Script nicht läuft, vermute ich mal, dass es Probleme gab und das Video dazu deshalb fehlt. Trifft das so zu? Kommt das Video noch? Die Erklärung zu dem Algorithmus würde mich sehr interessieren, da er nicht einfach zu verstehen ist.

**Comment by Gravitar64** [comment]
Hi,

ja, ab und zu habe ich im GitHub auch einige Versionen, die nicht als Video vorliegen. Da probiere ich dann irgendwas aus. Wie auch hier. 

Ein Video zu Brechen des Enigma-Codes ist aktuell nicht zu erwarten, da ich den Anspruch habe, den Weg von Alan Turing umzusetzen. Dazu gibt es allerdings sehr wenig Dokumentationen, wie er das wirklich im Detail gemacht hat.

**Comment by klaussoft** [comment]
Da könnte ich helfen. Inzwischen habe ich nach Videos und sehr vielen Dokumentationen verstanden, wie die Turingbombe und der ganze Vorgang funktioniert und kann sogar die Turingbombe bedienen. Ich bin gerade selbst dabei, diese nachzuprogrammieren, wobei das nur zum Teil geht, oder sinnvoll ist. Ein Hauptbestandteil ist das Prinzip, dass man Strom auf einen Kontakt gibt und nur ein ganz bestimmter Teil dabei stromführend werden darf. Es wird also erkannt, ob dabei Strom woanders raus kommt, was sich programmiertechnisch nicht, oder nur sehr uneffektiv umsetzen lässt. Programmiertechnisch gibt es da bessere Methoden.
Wir können uns gerne darüber mal austauschen. Allerdings denke ich, dass hier nicht der richtige Ort dafür ist. Leider finde ich nirgendwo eine Mailadresse von Dir. Deshalb hatte ich das hier rein geschrieben, weil ich keine bessere Kontaktmöglichkeit gefunden hatte.

**Comment by Gravitar64** [comment]
Interessant wäre eine Erklärung des Menus für die Turing-Bombe. Wie wird das Menu erstellt, was bewirkt das Menu usw. Dazu habe ich bisher noch nichts gefunden.

**Comment by klaussoft** [comment]
Wie gesagt, könnte ich Dir erklären. Am besten wäre dazu eine Konferenz 
mit Whiteboard. Erstellt hast Du das Menü ja schon, oder zimindest die 
Loop, wobei ich Deinen Algorithmus nicht richtig verstehe. Ich habe es 
zwar inzwischen, aber sehr uneffektiv und schlecht debugbar. Gibt es 
hier nicht irgendwie eine Kontaktmöglichkeit? Da könnten wir mal 
Kontakte austauschen und uns zusammen setzen. Ich kenne mich mit Github 
nicht so wirklich aus.
