### ISSUE TITLE
mandelbulb reference

### ISSUE THREAD

**Issue by WolfMS** [Gravitar64/A-beautiful-code-in-Python#13]
Hallo Gravitar, hi,
erstmal finde ich die Serie gut, habe etwas gelernt auch wenn ich mir nicht alles merken kann und einige Folgen mehrfach nacharbeiten muß.

 Ich hatte mir in den Formeln einen Fehler eingebaut und darum das script von github zum Vergleichen genommen.
 Habe da wohl noch eine ältere Version gehabt (jun.2022).
 
 Daraus ergeben sich 2 Probleme:
 1.
 Im script werden die Bereiche negativ/positiv initialisiert -> (-BEREICH,BEREICH)
 Die Darstellung nach der Berechnung schließt, entgegen der Ansage im Video, eine Spiegelsymmetrie in allen 3 Ebenen aus!
 Das System ist mit den gewählten Parameter N = 8 siebenstrahlig (7). Es gibt eine Rotationsachse und 
 auf dieser Achse gibt es auf den Polen a eine Auswölbung, b entgegengesetzt eine Eindellung, außerdem gibt
 es mehrere "Ringebenen", die gegeneinanderversetzt und nicht mittensymmetrisch sind.
 Ich habe jetzt noch nicht die Dokumentation zu "Ursina" studiert aber es scheint das die einzige Symmetrie (Ursina.y) ist
 
 Die Zahl der Ebenen und der "Strahlen" sieht von N abhängig aus ( N-1 Strahlen )
 Aus der Annahme folgen Versuche mit N = 7 bzw 9, die Darstellung scheint in allen drei (3) Ebenen Spiegelsymmetrisch!
 Mit N = 6 bzw 10 ergibt sich wieder eine unsymtrische Form.
 Mir fehlen die mathematischen Kenntnisse für eine/n Herleitung/Beweis!
 Meine monentane Lösung:
 
      punkte = []
      for x in range((BEREICH * (not (N % 2)) * -1),BEREICH):
          for y in range(BEREICH):
              hülle = False
              for z in range((BEREICH * (not(N % 2)) * -1),BEREICH):
                  if not punkt_in_fraktal(x, y, z): continue
                  
                  for m1, m2, m3 in iter.product([-1,1], repeat= 3):
                      if N % 2:
                          punkte.append((x*m1, y*m2, z*m3))
                      elif not N % 2:
                          punkte.append((x, y*m2, z))
 
 vielleich ist das ja noch Verbesserungswürdig.
 
 2.
 start = pfc() -> woher, pfc ist nicht deklariert/initialisiert
 export_ply_format('points.ply') -> mit welcher Bibliothek werden die Daten formatiert/exportiert? 
 Es gibt keine entsprechende "import"-Anweisung
 Ich habe im Netz einige Daten gefunden aber keine Hinweise zu der Benutzung in/mit python/ursina.

**Comment by Gravitar64** [comment]
zu 1)
ja, kann sein. Mir erschien es spiegelsymmetrisch. Allerdings habe ich das nicht tiefer untersucht. Man kann natürlich auch den Fraktal-Bereich in allen 3 Achsen auf -1,1 einstellen. Die Auflösung (bei mir 64) müsste dann diese Bereiche entsprechend unterteilen. Die Rechenzeit wäre dann natürlich 8x so hoch.

Ich meine sogar, dass ich das vorab getestet habe, aber keinen visuellen Unterschied feststellen konnte und dann wieder auf den symmetrischen Ansatz geschwenkt bin.

zu 2)
Im Source-Code finde ich kein pfc und auch kein export_ply etc
