### ISSUE TITLE
Teil4: visualisieren von PI

### ISSUE THREAD

**Issue by fsnobody** [Gravitar64/A-beautiful-code-in-Python#3]
Hallo,
ich bin mittlerweile bei dem 9.Youtube Tutorial
 und habe bis jetzt alle hingekriegt, nur bei Teil 4 dem visualisieren von Pi bin ich gescheitert. Selbst mit dem Code von hier bekomme ich folgende Fehlermeldung:
`zahl = int(pi[n])
ValueError: invalid literal for int() with base 10: '.'`

Ich danke schon mal im Voraus für Hilfe.

Gruß FS

**Comment by Gravitar64** [comment]
Hi, da hast du eine Textdatei genutzt, die noch den '.' von 3.141 benutzt. Entweder den . aus der Textdatei löschen oder meine Textdatei nutzen (da ist der Punkt bereits entfernt). Die Fehlermeldung sagt nur aus, dass der Versuch das Zeichen '.' in eine Integer-Zahl umzuwandeln gescheitert ist.
