### ISSUE TITLE
danke für deine gute arbeit

### ISSUE THREAD

**Issue by schnittenberg** [Gravitar64/A-beautiful-code-in-Python#4]
Als erstes, sorry für den möglicherweise unkonventionellen weg ;) aber ich habe tatsächlich keine möglichkeit gefunden dich "privat" anzuschreiben.Ich möchte dir gern eine kleine spende zukommen lassen (wirklich ne kleinigkeit) und hab halt kein paypal konto oder so gefunden. Ich finde einfach dass deine videos (mir persönlich) sehr helfen und du es sehr gut verständlich in einem angemessenen Tempo erklärst und wollte mich eben dafür inform einer spende bedanken weil ich finde dass das auch enorm zeit bedarf um das alles zu erklären.

Hoffe das kommt nicht irgendwie creepy rüber. falls doch ignorier es einfach.
In jedem Falle, weiter so und danke für deine Videos

**Comment by Gravitar64** [comment]
Das ist ja nett, habe tatsächlich noch gar nicht daran gedacht. Aber jetzt ganz frisch, hier der Spendenlink: 

https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=WW3XE87GT4TZ8&source=url
