### ISSUE TITLE
ich benötige ein wenig hilfe

### ISSUE THREAD

**Issue by hauckenberg** [Gravitar64/A-beautiful-code-in-Python#5]
Hallo Gravitar,
Ich könnte deine Hilfe für meine Bachelorarbeit benötigen.
Es geht um das erstellen eines Hypercubes im 3D-Program Autodesk Maya. 
Durch einlesen und dein Tutorial über das erstellen eines Hypercubes habe ich eine gute Basis aber ich scheitere an nicht vorhandenen Kenntnissen im Coding Bereich.
Falls du irgendwie Zeit findest und mir ein paar Tipps geben könntest wäre das super. 

email: dohauck@stud.mediadesign.de 

LG und vielen Dank für deine Arbeit.

**Comment by Gravitar64** [comment]
Sorry, aber da empfehle ich die Einarbeitung die die jeweilige Programmiersprache deiner Wahl. Wenn es Python ist, kannst du natürlich gern auf meine inzwischen > 40 Videos zugreifen. Da lernt man eine ganze Menge.
