### ISSUE TITLE
bei 49 Schach musste ich ['puzzle'] vor ['fen'] einfügen, um key-error zu bereinigen 

### ISSUE THREAD

**Issue by wernerwib** [Gravitar64/A-beautiful-code-in-Python#7]
fen = chess.get_random_daily_puzzle().json['fen']  
führte zu einer Fehlermeldung.

Nach json-Analyse habe ich die Zeile modifiziert:

fen = chess.get_random_daily_puzzle().json['puzzle']['fen']  

Dann hat es funktioniert.
Ich verwende python 3.8.3

**Comment by Gravitar64** [comment]
Je nach Version (Python + chess.com) ist mal 'puzzle' notwendig oder auch nicht. Bei Python 3.9.2 64bit + chess.com 21.0.1 ist das puzzle nicht notwendig.

Habe diesen Hinweis als Kommentar in den Source-Code eingefügt.

**Comment by wernerwib** [comment]
Als Dank für Ihre sehr hilfreichen Beispiele hier eine von mir erstellte grafische Version von "Vier gewinnt"

# ww_16_KI_grafisch_Vier_gewinnt

from collections import defaultdict
import time

import pygame as pg
import ww_17_pygame_functions as pgf
import winsound 

# Richtung (-1, -1) bedeutet
# schräg nach links unten; z.B. wird aus 1,1   0,0 beim Addieren
# Richtung (1, 1)   bedeutet schräg nach rechts oben; z.B. wird aus 1,1   2,2
# Richtung (0, 1)   bedeutet nach oben,               z.B. wird aus 1,1   1,2
RICHTUNGEN = [(-1, -1), (0, -1), (1, -1), (-1, 0),
              (1, 0), (-1, 1), (0, 1), (1, 1)]
SPALTEN = 7
ZEILEN = 6
ZELLEN = SPALTEN * ZEILEN
AUFLÖSUNG = 700         # Grö0e des Spielfelds
FELD = AUFLÖSUNG // 7   # Größe eines Felds = 100 Pixel 
BREITE = AUFLÖSUNG

pos_zu_quadindex = defaultdict(list)

spielfeld = {}

def feld2x(feldNr):
  x = feldNr % 7 * FELD     # feld % 7 liefert die Spalte, * 700/7 = 100 Pixel
  y = 0
  return x,y

def feldNr2xy(feldNr):        # feldnur to x y 
  #print('feldNr = ', feldNr)
  x = feldNr % 7 * FELD       # feldNr % 7 liefert die Spalte, * 700/7 = 100 Pixel
  y = (feldNr // 7) * FELD + FELD 
  #y = (feldNr // 7) * FELD 
  return x,y

def feld2xy(feldTupel):        # feldnur to x y 
  #print('feldTupel = ', feldTupel)
  x = feldTupel[0] % 7 * FELD     # feld % 7 liefert die Spalte, * 700/7 = 100 Pixel
  y = int((feldTupel[1]) * FELD + AUFLÖSUNG / 7)
  #y = int((feldTupel[1]) * FELD )  
  return x,y

def feldNr2zentrum(feldNr):
  x,y = feldNr2xy(feldNr)
  return x + FELD//2, y + FELD//2   # so kriege ich den Mittelpunkt des Feldes

def feld2zentrum(feldTupel):
  x,y = feld2xy(feldTupel)
  return x + FELD//2, y + FELD//2   # so kriege ich den Mittelpunkt des Feldes

def quadPositionen(pos, vec):
  positionen = set()
  sp, ze = pos
  rsp, rze = vec
  neue_sp, neue_ze = sp + rsp*3, ze+rze*3
  if neue_sp < 0 or neue_sp >= SPALTEN or neue_ze < 0 or neue_ze >= ZEILEN:
    return False
  for i in range(4):
    positionen.add((sp+rsp*i, ze+rze*i))
  return positionen


def findeQuads():
  zähler = 0
  quads = {}
  bekannte_positionen = set()
  for i in range(ZELLEN):
    for richtung in RICHTUNGEN:
      positionen = quadPositionen(i2pos(i), richtung)
      if not positionen or positionen in bekannte_positionen:
        continue
      quads[zähler] = [0, 0, positionen]  # Anzahl der gelben[0], roten[1] Steine im Quad
      for position in positionen:
        pos_zu_quadindex[position].append(zähler)
      bekannte_positionen.add(frozenset(positionen))
      zähler += 1
  return quads


def i2pos(i):
  return (i % SPALTEN, i // SPALTEN)


def findeTiefsteZeile(spalte):
  for zeile in reversed(range(ZEILEN)):
    if (spalte, zeile) not in spielfeld:
      return zeile


def spalteGültig(spalte):
  if (spalte, 0) in spielfeld:  # Spalte ist bis oben gefüllt.
    return False
  if 0 <= spalte < 7:           # Damit Spaltenwunsch größer 6 nicht akzeptiert wird.
    return True


def lieferSpalten():
  gültige_spalten = []
  for spalte in range(SPALTEN):
    gültige_spalten.append(spalte) if (spalte, 0) not in spielfeld else None
  return gültige_spalten


def steinSetzen(spieler, pos):
  gewonnen = False
  spielfeld[pos] = 'O' if spieler else 'X'
  for index in pos_zu_quadindex[pos]:
    try:                                      #zzzzzzzzzzzzzzzzzzzzzz   Exception Übung WW  zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
      quad = quads[index]
    except KeyError as ke:
      print ('index = ', index)
      print('pos_zu_quadindex[pos], pos = ', pos_zu_quadindex[pos], pos)
    #quad = quads[index]
    quad[spieler] += 1
    if quad[spieler] == 4:
      gewonnen = True
  return gewonnen

def steinLöschen(spieler, pos):
  del spielfeld[pos]
  for index in pos_zu_quadindex[pos]:
    quads[index][spieler] -= 1
  

def gültigeZüge():
  gültig = []
  for spalte in lieferSpalten():
    zeile = findeTiefsteZeile(spalte)
    gültig.append((spalte, zeile))
  return gültig


def printSpielfeld():
  for i in range(ZELLEN):
    print(spielfeld[i2pos(i)], end=' ') if i2pos(
        i) in spielfeld else print('.', end=' ')
    print() if (i+1) % SPALTEN == 0 else None


def zeigeSpielfeld():
  global reagiereAufEvents

  screen.fill((0,0,0))                # Rot Grün Blau  0 0 0 = schwarz

  pg.display.set_caption('Werners "4 gewinnt"        \
                                                    <--     v     -->')
  setzeCoinAufStartSpalte(startSpalte, spieler)

  for feldNr in range(42):
    #alles erst mal blaue Quadrate
    farbe = (0,0,255)  # blau
    pg.draw.rect(screen, farbe, (feldNr2xy(feldNr), (FELD, FELD)))
    #       Rechteck             x y von Feld    Breite Höhe des Rechtecks
    # Zeichenwurzel des Rechtecks ist dessen linke obere Ecke
    # Ergebnis: spielfeld ist ganz blau

  for feldNr in range(42):
    #jetzt 42 schwarze Kreise in die blauen Felder
    farbe = (0,0,0)    # schwarz
    pg.draw.circle(screen, farbe, feldNr2zentrum(feldNr), int(FELD*0.3))
    #lauter schwarze Kreise erst mal rein ins blaue spielfeld
 
  #jetzt rote oder gelbe Kreise an die Positionen setzen, die bisher besetzt wurden von Mensch oder Computer
  for i in range(ZELLEN):       # wohlgemerkt in 6*7 = 42 ZELLEN, nicht ZEILEN. i beginnt mit 0.
  
    pos = (i % SPALTEN, i // SPALTEN)   # Rest von i / 7,   Vorkommastelle von i / 7
    if pos in spielfeld:
      #print('spielfeld[pos] = ' , spielfeld[pos])
      for pos, stein in spielfeld.items():
        #print('pos = ',pos)            # pos also z.B. (0,5) unten links bis (0,0) oben links
                                        #               (6,5) unten rechts bis (6,0) oben rechts
                                        #               (6,5) = (rechte Spalte 6, unterste Zeile 5) 
        #print('stein = ',stein)        # stein also z.B. 'X'

        farbe = (255,0,0) if (stein == 'X') else (255,255,0)
        #print('feld2zentrum(pos) = ', feld2zentrum(pos) )
        pg.draw.circle(screen, farbe, feld2zentrum(pos), int(FELD*0.3))

  farbe = (0,0,0) 
  textfläche = pg.font.SysFont('courier', 16).render('0        1         2         3         4         5         6', False, farbe)
  screen.blit(textfläche,(55,80))         #(x, y) 
  
  #ggf. den gewinnerFarbtext anzeigen
  if gewinnerFarbtext != '':
    farbe = (0,0,255)
    textfläche = pg.font.SysFont('impact', 24).render(gewinnerFarbtext + ' ist Gewinner!', False, farbe)
    screen.blit(textfläche,(20,0))         #(x, y)
    textfläche = pg.font.SysFont('courier', 16).render(' <      >  für weiter, sonst: Esc und v', False, farbe)
    screen.blit(textfläche,(300,0))         #(x, y)
    # blit bringt binären Dateninhalt auf den screen
    winsound.Beep(2500,100)
    #winsound.PlaySound('point.wav', winsound.SND_FILENAME)

  
  #ggf. unentschieden anzeigen
  if unentschieden:
    farbe = (0,255,200)
    textfläche = pg.font.SysFont('impact', 24).render('...unentschieden...', False, farbe) 
    screen.blit(textfläche,(20,5))         #(x, y)
    # blit bringt binären Dateninhalt auf den screen
    winsound.Beep(2500,100)
    #winsound.PlaySound('point.wav', winsound.SND_FILENAME)

  #das oben Vorbereitete jetzt auf den screen bringen
  pg.display.flip()
  
  if gewinnerFarbtext != '' or unentschieden:
    #pg.time.wait(5000)  # in Millisekunden    # nicht mehr nötig
    initializeGame()
    pg.display.flip()


def bewertung():
  score = 0
  for pos in spielfeld:
    for index in pos_zu_quadindex[pos]:
      gelbe, rote, _ = quads[index]
      if gelbe > 0 and rote > 0:
        continue
      score += rote*10
      score -= gelbe*10
  return score


def löscheQuads():
  to_del = []
  for index, values in quads.items():
    if values[0] == 0 or values[1] == 0:
      continue
    to_del.append(index)
    for position in values[2]:
      pos_zu_quadindex[position].remove(index)
  for index in to_del:
    del quads[index]


def computer(spieler):
  print('computer(spieler) wurde aufgerufen')
  gewonnen = False
  score, bester_zug = minimax(8, -999999, 999999, spieler, gewonnen)
  gewonnen = steinSetzen(spieler, bester_zug)
  print(f'Spieler {1 if spieler else 2} setzt {bester_zug} mit der Bewertung {score}')
  return gewonnen


def minimax(tiefe, alpha, beta, spieler, gewonnen):
  if gewonnen:
    score = -99999-tiefe if spieler else 99999+tiefe
    return (score, None)
  if tiefe == 0 or len(spielfeld) == ZELLEN:
    return (bewertung(), None)
  value = -999999 if spieler else 999999
  for zug in gültigeZüge():
    gewonnen = steinSetzen(spieler, zug)
    score,_ = minimax(tiefe-1, alpha, beta, not spieler, gewonnen)
    steinLöschen(spieler,zug)
    if spieler:
      if score > value:
        bester_zug = zug
        value = score
        alpha = max(value, alpha)
    else:
      if score < value:
        bester_zug = zug
        value = score
      beta = min(value, beta)
    if alpha >= beta:
      break
  return (value, bester_zug)

def human(spalte, spieler):
  zeile = findeTiefsteZeile(spalte)
  gewonnen = steinSetzen(spieler, (spalte, zeile))
  print('Er setzt spalte, zeile = ', spalte, zeile)  
  return gewonnen

def gewonnen(spieler):
  #print('gewonnen(spieler)')
  stein = 'O' if spieler else 'X'
  for pos in spielfeld:
    for richtung in RICHTUNGEN:
      vier_in_einer_reihe = True
      for i in range(4):  # i geht von 0 bis 3
        spalte, zeile = pos
        delta_spalte, delta_zeile = richtung
        p1 = (spalte + delta_spalte*i, zeile + delta_zeile*i)      #  * 0 => alte Pos
        if p1 in spielfeld and spielfeld[p1] == stein: continue    # d.h. i wird hochgezählt
                                                                   # nicht etwa weiter zur Folgezeile
        vier_in_einer_reihe = False
        break     # raus aus 4er-Loop
      if vier_in_einer_reihe:
        return True
  #return False

def gewinnerFarbtextErmitteln(spieler):
  global gewinnerFarbtext
  gewinnerFarbtext = ' ROT' if spieler else 'GELB'
  return gewinnerFarbtext

def setzeCoinAufStartSpalte(startSpalte, spieler):
  # roter oder gelber Kreis über dem Spielfeld über spalte startSpalte
  for einwurfZeile in range(7):
    farbe = (255,255,255)             # weiß
    pg.draw.rect(screen, farbe, (feld2x(einwurfZeile), (FELD, FELD))) 
  farbe = (255,255,0) if spieler else (255,0,0)
  pg.draw.circle(screen, farbe, (startSpalte*FELD + FELD // 2, 0.5*FELD), int(FELD*0.3))


def initializeGame():
  global spielfeld, weitermachen, spieler, reagiereAufEvents, computerAmZug, quads, pos_zu_quadindex, \
    startSpalte, neuesSpielGewünscht, unentschieden, gewonnen, gewinnerFarbtext, dasWars
  spielfeld = {}
  spieler = True   #gelb
  gewinnerFarbtext = ''
  startSpalte = 3
  weitermachen = True
  neuesSpielGewünscht = True
  unentschieden = False
  gewonnen = False
  dasWars = False
  reagiereAufEvents = True
  computerAmZug = False
  quads = {}
  pos_zu_quadindex = defaultdict(list)
  quads = findeQuads()
  
pg.init()
screen = pg.display.set_mode([AUFLÖSUNG, AUFLÖSUNG])   # horinzontal2, vertikale Pixel
clock = pg.time.Clock()
clock.tick(20)
initializeGame()
zeigeSpielfeld()

start = time.perf_counter()
while weitermachen and neuesSpielGewünscht:
  #print('weitermachen, neuesSpielGewünscht = ', weitermachen, neuesSpielGewünscht)
  #print('spieler = ', spieler)

  while reagiereAufEvents:
    for event in pg.event.get():
      if event.type == pg.QUIT or (event.type == pg.KEYDOWN and event.key == pg.K_ESCAPE):
        weitermachen = False
        pg.quit
      
      elif event.type == pg.KEYDOWN and event.key == pg.K_ESCAPE:
        # dann neues Spiel gewünscht
        neuesSpielGewünscht = False
        weitermachen = False 
        pg.register_quit             

      elif event.type == pg.KEYDOWN and event.key == pg.K_LEFT:
        if startSpalte > 0:
          startSpalte -= 1
          setzeCoinAufStartSpalte(startSpalte, spieler)
          zeigeSpielfeld()
      elif event.type == pg.KEYDOWN and event.key == pg.K_RIGHT:
        if startSpalte < 6:
          startSpalte += 1
          setzeCoinAufStartSpalte(startSpalte, spieler)
          zeigeSpielfeld()
      
      elif event.type == pg.KEYDOWN and event.key == pg.K_DOWN:
        reagiereAufEvents = False
        spalte = startSpalte
        if spalteGültig(spalte):
          print('human wird aufgerufen für spalte, spieler = ', spalte, spieler)
          gewonnen = human(spalte, spieler)
          if not gewonnen:
            printSpielfeld()
            zeigeSpielfeld()
            spieler = not spieler
            computerAmZug = True
          else:
            print('Endlich hat mal ein Mensch gegen den Computer gewonnen!')
            gewinnerFarbtext = gewinnerFarbtextErmitteln(not spieler)
            zeigeSpielfeld()
            pg.display.flip()
            initializeGame()
        else:
          reagiereAufEvents = True 
  
  if computerAmZug:    # wenn Computer
    gewonnen = computer(spieler)
    printSpielfeld()
    zeigeSpielfeld()
    löscheQuads()
    computerAmZug = False
    reagiereAufEvents = True
    #zeigeSpielfeld()
    startSpalte = 3
    setzeCoinAufStartSpalte(startSpalte, not spieler)

    farbe = (0,0,0) 
    textfläche = pg.font.SysFont('courier', 16).render('0        1         2         3         4         5         6', False, farbe)
    screen.blit(textfläche,(55,80))         #(x, y) 
    
    pg.display.flip()
    if gewonnen:
      print('Computer hat leider (mal wieder) gewonnen...')
      print(time.perf_counter()-start)
      gewinnerFarbtext = gewinnerFarbtextErmitteln(not spieler)
      zeigeSpielfeld()
      pg.display.flip()
      initializeGame()
      spieler = not spieler

  if weitermachen:
    spieler = not spieler

pg.quit()

**Comment by wernerwib** [comment]
Sorry,
die Formatierung ging verloren.
Deshalb erneut.... habe aus .py .txt gemacht, weil .py nicht akzeptiert wurde... Hoffentlich diesmal besser....
[ww_16_KI_grafisch_Vier_gewinnt.txt](https://github.com/Gravitar64/A-beautiful-code-in-Python/files/6309648/ww_16_KI_grafisch_Vier_gewinnt.txt)
