### ISSUE TITLE
Vorschlag: Erweiterung zum Dreieckspuzzle

### ISSUE THREAD

**Issue by techrabbit58** [Gravitar64/A-beautiful-code-in-Python#9]
Automatisierte Erzeugung der "Bauanleitung" für den DFS-Algorithmus:
https://github.com/techrabbit58/Tiles

Der Output der Generatorfunktion kann direkt von der dfs() Funktion als Wert des globalen "kanten" Dictionaries verarbeitet werden. Dass der Generator ein um 60° gedrehtes Kantenschema verwendet, ist anscheinend kein Problem.

Fundort: https://github.com/techrabbit58/Tiles (Ich bin mir nicht sicher, ob YT meine Antwort in der Kommentarsektion genommen hat.)

Viele Grüße
Dieter
..

**Comment by Gravitar64** [comment]
Hallo Dieter,

wow, ziemlich beeindruckend! Anscheinend war meine Vermutung richtig, dass die Ermittlung der Kantenvergleiche deutlich umfangreicher (50 Zeilen) ist als die eigentliche Lösung des Rätsels (15 Zeilen). 

Aber vielen Dank für die Anregung! Nett auch die Idee mit den NamedTuples. Dadurch wird die Lesbarkeit nochmals deutlich verbessert 👍
